name: Build for TVBox

on: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Build for ARMv7l
        run: |
          export CC=arm-linux-gnueabihf-gcc
          export CXX=arm-linux-gnueabihf-g++
          ./configure --host=arm-linux-gnueabihf --prefix=/usr/arm-linux-gnueabihf
          make
          
      - name: Save Exec
        uses: actions/upload-artifact@v4
        with:
          name: udpxy.armv7l
          path: 
