name: Check Repository Path
on:
  push:
    branches:
      - main

jobs:
  check-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print repository path
        run: pwd
