name: Check Repository Path

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Optional message for the run'
        required: false
        default: 'Manual run'

jobs:
  check-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print repository path
        run: pwd
